# Generated by Django 3.1.3 on 2020-11-26 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.IntegerField(unique=True)),
                ('Name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=50)),
                ('Mobile_no', models.IntegerField(max_length=10)),
            ],
        ),
    ]
